# ComfyUI Dynamic Builder Configuration

# Base image configuration
base:
  image: "python:3.10-slim"
  platforms:
    - "linux/amd64"  # Future: linux/arm64

# Build variants
variants:
  - name: "nvidia"
    tag: "v1.0.0"
    base_image: "nvidia/cuda:11.8.0-runtime-ubuntu22.04"
    cuda_version: "11.8"
    description: "ComfyUI with NVIDIA CUDA support"
    env:
      PYTHONUNBUFFERED: "1"
      DEBIAN_FRONTEND: "noninteractive"
    packages:
      - file: "config/os-packages.txt"
      - file: "config/requirements-comfyui.txt"
      - custom:
        - "torch==2.0.1+cu118"
        - "torchvision==0.15.2+cu118"
        - "torchaudio==2.0.2+cu118"
        - "--extra-index-url https://download.pytorch.org/whl/cu118"
    scripts:
      - "scripts/start-comfyui-manager.sh"

  - name: "cpu"
    tag: "v1.0.0"
    base_image: "python:3.10-slim"
    description: "ComfyUI with CPU support only"
    env:
      PYTHONUNBUFFERED: "1"
      DEBIAN_FRONTEND: "noninteractive"
    packages:
      - file: "config/os-packages.txt"
      - file: "config/requirements-comfyui.txt"
      - custom:
        - "torch==2.0.1+cpu"
        - "torchvision==0.15.2+cpu"
        - "torchaudio==2.0.2+cpu"
        - "--extra-index-url https://download.pytorch.org/whl/cpu"
    scripts:
      - "scripts/start-comfyui-manager.sh"

# Build settings
build:
  repository: "comfyui"
  registry: "quay.io/opendatahub"
  comfyui_repo: "https://github.com/comfyanonymous/ComfyUI.git"
  comfyui_version: "master"
  workdir: "/opt/app-root/src"
  port: 8080
  user: 1001 