# ComfyUI Dynamic Builder Configuration

# Base image configuration
base:
  image: "registry.access.redhat.com/ubi9/python-311"
  platforms:
    - "linux/amd64"  # Future: linux/arm64

# Build variants
variants:

  - name: "cpu"
    tag: "v1.0.0"
    base_image: "registry.access.redhat.com/ubi9/python-311"
    description: "ComfyUI with CPU support only"
    env:
      PYTHONUNBUFFERED: "1"
      DEBIAN_FRONTEND: "noninteractive"
    packages:
      - file: "config/os-packages.txt"
      - file: "config/requirements-comfyui.txt"
      - custom:
        - "torch==2.7.1+cpu"
        - "torchvision==0.22.1+cpu"
        - "torchaudio==2.7.1+cpu"
        - "--extra-index-url https://download.pytorch.org/whl/cpu"
    scripts:
      - "scripts/start-comfyui.sh"

  - name: "nvidia"
    tag: "v1.0.0"
    base_image: "nvcr.io/nvidia/cuda:12.8.0-runtime-ubi9"
    cuda_version: "12.8"
    description: "ComfyUI with NVIDIA CUDA support"
    env:
      PYTHONUNBUFFERED: "1"
      DEBIAN_FRONTEND: "noninteractive"
    packages:
      - file: "config/os-packages.txt"
      - file: "config/requirements-comfyui.txt"
      - custom:
        - "torch==2.7.1+cu128"
        - "torchvision==0.22.1+cu128"
        - "torchaudio==2.7.1+cu128"
        - "--extra-index-url https://download.pytorch.org/whl/cu128"
    scripts:
      - "scripts/start-comfyui.sh"

# Build settings
build:
  repository: "comfyui"
  registry: "ghcr.io/gpillon"
  comfyui_repo: "https://github.com/comfyanonymous/ComfyUI.git"
  comfyui_version: "master"
  workdir: "/opt/app-root/src"
  port: 8080
  user: 1001 

# Custom ComfyUI packages to install at build time
comfyui_packages:
  - name: "ComfyUI-Manager"
    repo: "https://github.com/ltdrdata/ComfyUI-Manager.git"
    path: "custom_nodes/ComfyUI-Manager"
    enabled: true
  # Add more packages as needed following the same format:
  # - name: "Package-Name"
  #   repo: "https://github.com/author/repo.git"
  #   path: "custom_nodes/Package-Name"
  #   enabled: true 